import React from "react";
export const FontsData = [
  {
    numberOfStyles: "1",
    fontName: "Menor",
    img: "ageer.webp",
    font: 'Georgia, "Times New Roman", Times, serif',
    link: "/",
    avatar: "default_07.png",
    creator: "Ahmaddramz",
  },
  {
    numberOfStyles: "1",
    fontName: "Chadelova",
    img: "1-thumb2x.webp",
    font: '"Apple Chancery", cursive',
    link: "/",
    avatar: "default_08.png",
    creator: "Twinletter",
  },
  {
    numberOfStyles: "1",
    fontName: "Qatora",
    img: "Qatora-01-thumb2x.webp",
    font: "Trattatello, fantasy",
    link: "/",
    avatar: "default_01.png",
    creator: "Letterhend",
  },
  {
    numberOfStyles: "1",
    fontName: "Delliger",
    img: "Delliger-01.webp",
    font: "OCR A Std, monospace",
    link: "/",
    avatar: "youngtype.jpg",
    creator: "youngtype",
  },
  {
    numberOfStyles: "1",
    fontName: "Watchout",
    img: "Cover-thumb2x.jpg",
    font: "Snell Roundhand, cursive",
    link: "/",
    avatar: "default_08.png",
    creator: "GassType",
  },
  {
    numberOfStyles: "14",
    fontName: "Takashimura",
    img: "Takashimura_1-thumb2x.webp",
    font: "Chalkduster, fantasy",
    avatar: "default_08.png",
    creator: "GassType",
    link: "/",
  },
  {
    numberOfStyles: "1",
    fontName: "Stormlight",
    img: "Stormlight-thumb2x.webp",
    font: "Luminari, fantasy	",
    avatar: "default_08.png",
    creator: "GassType",
    link: "/",
  },
  {
    numberOfStyles: "2",
    fontName: "Orange Milk",
    img: "orangemilk.webp",
    font: "Blippo, fantasy",
    avatar: "default_07.png",
    creator: "AlmarkhaType",
    link: "/",
  },
  {
    numberOfStyles: "2",
    fontName: "Nathain Script",
    img: "Nathain-thumb2x.webp",
    font: "Snell Roundhand, cursive	",
    avatar: "youngtype.jpg",
    creator: "youngType",
    link: "/",
  },
  {
    numberOfStyles: "2",
    fontName: "Marthens",
    img: "1-preview.webp",
    font: "Snell Roundhand, cursive	",
    avatar: "youngtype.jpg",
    creator: "youngType",
    link: "/",
  },
  {
    numberOfStyles: "1",
    fontName: "Sugarless Coffee",
    img: "sugarless-coffee1-preview.jpg",
    font: "Brush Script MT, Brush Script Std, cursive",
    link: "/",
    avatar: "default_08.png",
    creator: "GassType",
  },
  {
    numberOfStyles: "1",
    fontName: "Growlies",
    img: "Artboard-1-preview.webp",
    font: "Brush Script MT, Brush Script Std, cursive",
    link: "/",
    avatar: "default_01.png",
    creator: "Letterhend",
  },
  {
    numberOfStyles: "2",
    fontName: "Billy Money",
    img: "Billy_Money_1-preview.jpg",
    font: "Arial, sans-serif	",
    link: "/",
    avatar: "default_01.png",
    creator: "Alit Design",
  },
  {
    numberOfStyles: "1",
    fontName: "The last Shuriken",
    img: "Cover-preview.webp",
    font: "Avantgarde, TeX Gyre Adventor, URW Gothic L, sans-serif	",
    link: "/",
    avatar: "default_07.png",
    creator: "Ahmaddramz",
  },
  {
    numberOfStyles: "1",
    fontName: "Chadelova",
    img: "REBOG-01-preview.webp",
    font: "Palatino, URW Palladio L, serif",
    link: "/",
    avatar: "default_08.png",
    creator: "Twinletter",
  },
];
